services:
#
  zabbix-server:
    extends:
      file: common-logging.yml
      service: base-service
    build:
      context: ./zabbix-server/
    environment:
      TZ: Asia/Tokyo
      LANG: C
      LANGUAGE: C
      LC_ALL: C
    restart: unless-stopped
    depends_on:
      zabbix-database:
        condition: service_healthy
    networks:
       - frontend_bridge
       - database_network_default
#
  zabbix-database:
    extends:
      file: common-logging.yml
      service: base-service
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DB:-zabbix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - database-store:/var/lib/postgresql/data
    networks:
      database_network_default:
        aliases:
          - database
#
  zabbix-database-webmin:
    extends:
      file: common-logging.yml
      service: base-service
    image: dpage/pgadmin4:latest
    environment:
      TZ: Asia/Tokyo
      LANG: C
      LANGUAGE: C
      LC_ALL: C
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@localhost.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    restart: unless-stopped
    healthcheck:
       test: wget -O - http://localhost:80/misc/healthcheck
       interval: 10s
       timeout: 1s
       retries: 3
       start_period: 10s
    volumes:
       - pgadmin-store:/var/lib/pgadmin
    networks:
       - frontend_bridge
       - database_network_default
    ports:
       - "${PGADMIN_WEBPORT:-30001-30200}:80"

volumes:
  pgadmin-store:
  database-store:
networks:
  frontend_bridge:
  database_network_default:
    driver: bridge
    internal: true
